Migration from size-satisfies to workspaces
NodeSecure/cli pull request #302
Opened 2023-12-03 19:55 UTC by fabnguess

2023-12-03 21:47 UTC, PierreDemailly commented
Also don't forget to update https://github.com/NodeSecure/cli#workspaces

2023-12-03 22:26 UTC, PierreDemailly commented on workspaces/size-satisfies/README.md
> +<!-- ALL-CONTRIBUTORS-LIST:END -->
Please do not resolve when fixes is not pushed ^^

2023-12-04 01:01 UTC, fraxken requested changes

2023-12-04 01:01 UTC, fraxken commented on workspaces/size-satisfies/package.json
> +  "homepage": "https://github.com/NodeSecure/size-satisfies#readme",
Need to update those links

2023-12-04 11:24 UTC, merged